# Generated by Django 3.2.16 on 2024-02-18 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipu',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('name', models.CharField(max_length=50, verbose_name='食谱名称')),
                ('Ingredients', models.TextField(verbose_name='食材')),
                ('method', models.TextField(verbose_name='做法')),
                ('Heat', models.CharField(max_length=50, verbose_name='热量')),
                ('carbohydrates', models.CharField(max_length=50, verbose_name='碳水化合物')),
                ('fat', models.CharField(max_length=50, verbose_name='脂肪')),
                ('protein', models.CharField(max_length=50, verbose_name='蛋白质')),
                ('cellulose', models.CharField(max_length=50, verbose_name='纤维素')),
            ],
            options={
                'verbose_name': '食谱表',
                'verbose_name_plural': '食谱表',
                'db_table': 'Shipu',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('userName', models.CharField(max_length=20, verbose_name='姓名')),
                ('userSex', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=4, verbose_name='性别')),
                ('userAge', models.CharField(default='20', max_length=20, verbose_name='年龄')),
                ('usersg', models.CharField(default='20', max_length=20, verbose_name='身高')),
                ('usertz', models.CharField(default='20', max_length=20, verbose_name='体重')),
                ('userst', models.CharField(default='20', max_length=20, verbose_name='身体活动水平')),
                ('userxt', models.CharField(default='20', max_length=20, verbose_name='血糖')),
                ('usersr', models.CharField(default='20', max_length=20, verbose_name='生日')),
                ('userPhoneNum', models.CharField(default='', max_length=20, verbose_name='电话')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Shipu_tuijian',
            fields=[
                ('createtime', models.DateTimeField(auto_created=True)),
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('shipu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shipu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '食谱推荐信息表',
                'verbose_name_plural': '食谱推荐信息表',
                'db_table': 'Shipu_tuijian',
            },
        ),
    ]
