# Generated by Django 4.1.7 on 2024-03-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_shipu_shipu_tuijian_users"),
    ]

    operations = [
        migrations.RemoveField(model_name="shipu_tuijian", name="shipu",),
        migrations.RemoveField(model_name="shipu_tuijian", name="user",),
        migrations.RemoveField(model_name="users", name="usersg",),
        migrations.RemoveField(model_name="users", name="userst",),
        migrations.RemoveField(model_name="users", name="usertz",),
        migrations.RemoveField(model_name="users", name="userxt",),
        migrations.DeleteModel(name="Shipu",),
        migrations.DeleteModel(name="Shipu_tuijian",),
    ]
