# Generated by Django 4.2 on 2024-05-04 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_shipu_tuijian_shipu_remove_shipu_tuijian_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="alldata",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="uuid",
                    ),
                ),
                ("k1", models.TextField(max_length=20, verbose_name="地点")),
                (
                    "k2",
                    models.TextField(
                        choices=[("男", "男"), ("女", "女")],
                        default="男",
                        max_length=4,
                        verbose_name="建立时间",
                    ),
                ),
                (
                    "k3",
                    models.TextField(default="20", max_length=20, verbose_name="建立朝代"),
                ),
                (
                    "k4",
                    models.TextField(default="20", max_length=20, verbose_name="地址"),
                ),
                ("k5", models.TextField(default="", max_length=20, verbose_name="面积")),
                ("k6", models.TextField(max_length=20, verbose_name="简介")),
            ],
            options={
                "verbose_name": "数据表",
                "verbose_name_plural": "数据表",
                "db_table": "alldata",
            },
        ),
        migrations.DeleteModel(name="Users",),
    ]
