# Generated by Django 4.2 on 2024-05-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alldata_delete_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alldata",
            name="k1",
            field=models.TextField(default="", verbose_name="地点"),
        ),
        migrations.AlterField(
            model_name="alldata",
            name="k2",
            field=models.TextField(default="", verbose_name="建立时间"),
        ),
        migrations.AlterField(
            model_name="alldata",
            name="k3",
            field=models.TextField(default="", verbose_name="建立朝代"),
        ),
        migrations.AlterField(
            model_name="alldata",
            name="k4",
            field=models.TextField(default="", verbose_name="地址"),
        ),
        migrations.AlterField(
            model_name="alldata",
            name="k5",
            field=models.TextField(default="", verbose_name="面积"),
        ),
        migrations.AlterField(
            model_name="alldata",
            name="k6",
            field=models.TextField(default="", verbose_name="简介"),
        ),
    ]
